Add missing required_files to run remotely
Fix the following error:

```
Fatal error: cannot open file '/jetstream2/scratch/main/jobs/65039573/tool_files/scripts/compare.R': No such file or directory
```