Fix Bioimaging inference tool (#1580)
* update model order

* update main

* add support for png

* update tests

* update tests

* update methods

* add tests

* fix formatting

* Add missing required_files to run remotely (#1577)

* Add missing required_files to run remotely

Fix the following error:

```
Fatal error: cannot open file '/jetstream2/scratch/main/jobs/65039573/tool_files/scripts/compare.R': No such file or directory
```

* Replace ubuntu-20.04 runner

https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/

* Lint R scripts

* remove bioimaging.core

* update tool version

* add input param information

* add end of file line

* update output files

* add image_diff for comparing tiff images in tests

* update tests

* rerun tests

---------

Co-authored-by: Nicola Soranzo <nicola.soranzo@earlham.ac.uk>