Add missing required_files to run remotely (#1577)
* Add missing required_files to run remotely

Fix the following error:

```
Fatal error: cannot open file '/jetstream2/scratch/main/jobs/65039573/tool_files/scripts/compare.R': No such file or directory
```

* Replace ubuntu-20.04 runner

https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/

* Lint R scripts