Fix inforna broken XML
Fix:

```
galaxy.util ERROR: Error parsing file /home/runner/work/autoupdate/autoupdate/tools_repo/tools/rna_tools/inforna/inforna.xml
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/galaxy/util/__init__.py", line 381, in parse_xml
    tree = cast(ElementTree, etree.parse(f, parser=parser))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3711, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 2052, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 2070, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1965, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1254, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 647, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 765, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 689, in lxml.etree._raiseParseError
  File "/home/runner/work/autoupdate/autoupdate/tools_repo/tools/rna_tools/inforna/inforna.xml", line 38
lxml.etree.XMLSyntaxError: attributes construct error, line 38, column 54
Error loading tool with path /home/runner/work/autoupdate/autoupdate/tools_repo/tools/rna_tools/inforna/inforna.xml
```

Also:
- Use profile
- Add macros for version and suffix
- Fix broken command line
- Single-quote text parameters and output files
- Add `argument` attribute to `params`
- Remove unused parameters
- Fix output datatype
- Fix test
- Update test output file